### ISSUE TITLE
更换勋章的弹窗显示在了弹幕框中

### ISSUE THREAD

**Issue by maobowen** [xfgryujk/blivemedal#4]
如图，感觉是个bug？之前一段时间还是好好的弹窗，就是最近变成了这样。

![Screenshot](https://user-images.githubusercontent.com/14121443/121846748-5b150200-cc9c-11eb-80ac-8dd0ae875eb6.gif)

不同电脑不同浏览器都是如此。已经确认直播间只有这一个油猴脚本运行，关闭[同传字幕过滤插件](https://github.com/eric2788/bilibili-jimaku-filter)后问题依然没有解决，因此基本可以确认是这个脚本的问题。不知道是不是B站最近更新了直播间的HTML。

环境：
- 系统：macOS Big Sur 11.4
- 浏览器：Chrome 91, Chrome Beta 93
- Tampermonkey: v4.13.6137

**Comment by xfgryujk** [comment]
我这里没复现...

**Comment by Leo12025** [comment]
深色模式下的bug（已经确认

**Comment by maobowen** [comment]
我不会Vue，但稍微看了下，如果把 [`medalDialog`](https://github.com/xfgryujk/blivemedal/blob/6e0c0215e590e3112bd332e50f8db45edead55f8/blivemedal.user.js#L162) 这个 div 移到 `#control-panel-ctnr-box` 之外、与 `#chat-control-panel-vm` 平级好像就可以了。不造实现起来有多困难，以及会不会引入其他 bug。

![screenshot](https://user-images.githubusercontent.com/14121443/122000956-764b4480-cd64-11eb-92f7-a605798febc9.gif)
