### ISSUE TITLE
无法获取勋章列表

### ISSUE THREAD

**Issue by yokinanya** [xfgryujk/blivemedal#5]
基本确定是b站改了东西，所有类似脚本都这样，控制台报错都一样
![IPTJMZ)V7S_QN7DJBZ$Q@1K](https://user-images.githubusercontent.com/30362789/135272635-4dddb932-3bc4-44bb-bcb5-c56190c2ea2b.jpg)

**Comment by xfgryujk** [comment]
明天或者后天修吧
